apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: django-todo
  template:
    metadata:
      labels:
        app: django-todo
    spec:
      containers:
      - image: manoj3699/django-todo:latest
        name: django-todo
        ports:
        - containerPort: 80
